### ISSUE TITLE
example

### ISSUE THREAD

**Issue by boardmain** [mcongrove/com.mcongrove.slideMenu#1]
hi can you provide a simply full example?
i tried to use it with  a blank new app but notting appear

**Comment by demogar** [comment]
@boardmain I had the same issue and just [discovered here](https://github.com/mcongrove/ChariTi/blob/master/app/lib/core.js#L893) that you need to define left property on open.

Hope it helps :)

**Comment by stephenwoodford** [comment]
For anyone else that runs into this, the corrected example would be:

```
function openMenu() {
    $.SlideMenu.Wrapper.left = "0dp";
    $.AppWrapper.animate({
        left: "200dp",
        duration: 250,
        curve: Ti.UI.ANIMATION_CURVE_EASE_IN_OUT
    });
}
```

**Comment by mcongrove** [comment]
Stupid GitHub, didn't even see a notification for this.

Thanks for pointing this out. The way we have the styling for the menu, by default, puts it at -200 left. You can animate it in with the slide (I've updated the README example), or you can go in and set it to 0 (as @demogar and @swoodford5 pointed out).
